server:
  port: 8104

spring:
  ratelimiter:
    zookeeper:
      zk-connect-str: 127.0.0.1:2181
      root-node: /configserver/userproject
      node: ratelimit-group
      config-version: 1.0.0
      config-key: rateLimit1
    config-type: json
    enable-monitor: true
    monitor-interval: 3
  application:
    name: zookeeper-example

# 对接prometheus
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'