{
 "title": "限流监控",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(rate_limiter_tokens_left, app_name)"
    }
   },
   {
    "name": "rate_limiter_key",
    "label": "RateLimiterKey",
    "query": {
     "query": "label_values(rate_limiter_tokens_left, rate_limiter_key)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "限流资源使用情况",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate_limiter_tokens_left{app_name=\"$application\", rate_limiter_key=\"$rate_limiter_key\"}"
    }
   ]
  },
  {
   "title": "拒绝请求数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate_limiter_reject_count{app_name=\"$application\", rate_limiter_key=\"$rate_limiter_key\"}",
     "legendFormat": "拒绝请求数"
    }
   ]
  },
  {
   "title": "限流器参数",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate_limiter_capacity{app_name=\"$application\", rate_limiter_key=\"$rate_limiter_key\"}",
     "legendFormat": "限流器容量"
    },
    {
     "expr": "rate_limiter_rate{app_name=\"$application\", rate_limiter_key=\"$rate_limiter_key\"}",
     "legendFormat": "限流器令牌生成速率"
    }
   ]
  }
 ]
}